run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - gofmt
    - goimports

linters-settings:
  misspell:
    locale: US
  goimports:
    local-prefixes: torrentstream

issues:
  exclude-dirs:
    - vendor
  max-issues-per-linter: 50
  max-same-issues: 10
