name: Feature Request
description: Suggest a new feature or improvement
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please describe your idea below.

  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What problem does this feature solve? What's the current pain point?
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this to work?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Any alternative solutions or workarounds you've considered?
    validations:
      required: false

  - type: dropdown
    id: area
    attributes:
      label: Area
      options:
        - Frontend (Web UI)
        - Video Player
        - Torrent Engine
        - Search
        - Deployment / Docker
        - API
        - Other
    validations:
      required: true
